apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-dl-deployment-contenedor-ia
spec:
  selector:
    matchLabels:
      app: kubermatic-dl
  replicas: 3
  template:
    metadata:
      labels:
        app: kubermatic-dl
    spec:
     containers:
     - name: kubermatic-dl
       #image: kubermatic00/kubermatic-dl:latest
       image: jeicson/contenedor.ia:v1
       imagePullPolicy: Always
       ports:
       - containerPort: 8080